-- Create Word table
CREATE TABLE IF NOT EXISTS Word (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    Token NVARCHAR(60) UNIQUE NOT NULL,
    CONSTRAINT C_Token CHECK(LENGTH(Token) >= 3)
);
-- Create Link table
CREATE TABLE IF NOT EXISTS Link (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    Path NVARCHAR(1024) UNIQUE NOT NULL,
    Score FLOAT,
    CONSTRAINT C_Path CHECK(Path <> '')
);
-- Create WordToLink table
CREATE TABLE IF NOT EXISTS WordToLink (
    WordID INTEGER NOT NULL,
    LinkID INTEGER NOT NULL,
    Count INTEGER NOT NULL,
    PRIMARY KEY (WordID, LinkID),
    FOREIGN KEY (WordID) REFERENCES Word (ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (LinkID) REFERENCES Link (ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT C_Count CHECK(Count > 0)
);
-- Create Graph table
CREATE TABLE IF NOT EXISTS Graph (
    Source INTEGER NOT NULL,
    Destination INTEGER NOT NULL,
    Count INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (Source, Destination),
    FOREIGN KEY (Source) REFERENCES Link (ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (Destination) REFERENCES Link (ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT C_Count CHECK(Count > 0)
);

-- Create LinksRank table
-- CREATE TABLE IF NOT EXISTS LinksRank (
--     LinkID INTEGER NOT NULL,
--     Score INTEGER,
--     FOREIGN KEY (LinkID) REFERENCES Word (ID)
--         ON DELETE NO ACTION ON UPDATE NO ACTIO
-- )